# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc167e60996ca619506f8ac5e2369df4b068c17beaf2a1b4f13b0f01a1312c08d30b37cdf6a6b8028201c6fa84fdad604b4e328bbef1b7dda5b71d485d70018c

test:
  secret_key_base: 16f04de7dca4299ef9956134921f9552a7afaa5683ee2e5ebacaf0ffbaec28cdad8df6c7865940e978d2cb865ee39aacbd40e67fea821e0dd6bcd6f8e3e986fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
